name: Your New Jekyll Site
owner:
  name: Ozan Keysan
  position: Lecturer
  department: Electrical-Electronics Engineering
  departmentweb: http://eee2.metu.edu.tr
  company: Mıddle East Technical University
  companyweb: http://www.metu.edu.tr
  avatar: ozan.jpg

#markdown: redcarpet
#redcarpet:
#  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables",     #"with_toc_data"]

markdown: kramdown
pygments: true
